# Релиз 2.0

## Импортируем библиотеки

In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.display.max_columns = None

## Начинаем работу с колонками

In [2]:
df = pd.read_csv('/home/cdxxi/Загрузки/_data.csv')

In [3]:
df

,Unnamed: 0,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,Описание,Ремонт,"Площадь комнат, м2",Балкон,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский,NaN,NaN,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.00,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский,25 25 20 25,NaN,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.50,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт,NaN,NaN,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.20,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086
3,3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...","+79660342340, +79099269384",ID 31618: Эксклюзивное предложение. Современн...,Евроремонт,14-42-20-19,NaN,На улицу и двор,Совмещенный (3),Можно с животными,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",NaN,NaN,3.20,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456
4,4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",+79852432860,Лот 111542. Татьяна Лучкина.\n\nБонус агенту 5...,Евроремонт,20 18,NaN,На улицу и двор,Совмещенный (2),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",The Book,NaN,3.90,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,23363,215565511,NaN,Квартира,м. Говорово (8 мин пешком),"Москва, Боровское шоссе, 2к7, ш. Боровское (3 ...",35.0/16.4/8.0,10/14,NaN,"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",+79154383401,Сдаётся светлая теплая квартира (студия) с бал...,Евроремонт,NaN,Балкон (1),NaN,Совмещенный (1),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",Мещерский лес,NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/215565511
23364,23364,274654844,1,Квартира,м. Солнцево (7 мин пешком),"Москва, Производственная улица, 8к1, ш. Боровс...",38.7/16.5/11.0,"5/18, Монолитный",NaN,"45000.0 руб./ За месяц, Залог - 45000 руб., Ко...",+79151173402,Сдам однокомнатную квартиру на длительный срок...,Евроремонт,NaN,Лоджия (1),Во двор,Совмещенный (1),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",Лучи,NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/274654844
23365,23365,268679909,"2, Оба варианта",Квартира,м. Солнцево (6 мин пешком),"Москва, Боровский проезд, 11",43.1,"5/5, Кирпичный",NaN,"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",+79653825192,Рассматриваются квартиранты только славяне и т...,Дизайнерский,NaN,Балкон (1),На улицу и двор,Совмещенный (1),Можно с детьми,"Мебель на кухне, Душевая кабина, Стиральная ма...",NaN,NaN,NaN,NaN,NaN,https://www.cian.ru/rent/flat/268679909
23366,23366,274807525,2,Квартира,м. Солнцево (11 мин пешком),"Москва, улица Богданова, 6к1, ш. Боровское (3 ...",52.5/10.0,"8/23, Монолитный",наземная,"55000.0 руб./ За месяц, Залог - 50000 руб., Ко...",+79660611965,Двухкомнатная уютная квартира с видом во внутр...,Евроремонт,NaN,Лоджия (1),Во двор,"Совмещенный (1), Раздельный (1)",NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",NaN,NaN,2.65,Пасс (3),Да,https://www.cian.ru/rent/flat/274807525
23367,23367,274672243,"2, Оба варианта",Квартира,м. Говорово (10 мин пешком),"Москва, улица Богданова, 2к1, ш. Боровское (3 ...",90.0/48.2/15.5,"6/23, Панельный",NaN,"57000.0 руб./ За месяц, Залог - 60000 руб., Ко...",+79623641533,Сдается просторная двухкомнатная квартира ВПЕР...,Косметический,"26,2+15,5-22,0",Лоджия (1),Во двор,Раздельный (1),"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Сти...",NaN,NaN,NaN,Пасс (3),Да,https://www.cian.ru/rent/flat/274672243

In [4]:
#Выкидываем ненужные колонки
df = df.drop(columns=['Серия дома', 'Ссылка на объявление', 'Телефоны', 'Описание', 'Unnamed: 0', 'Название ЖК', 'Можно с детьми/животными', 'Тип'])

In [5]:
#Исправили цену (теперь только цена/мес)
def price(s):
    return int(s.split('.')[0])

df['Цена'] = df['Цена'].apply(price)

In [6]:
#Удалим дубликаты по ID
df.drop_duplicates(subset=['ID  объявления'], keep='first', inplace=True)

In [7]:
#Удаляем все, кроме Москвы
df = df[df['Адрес'].str.contains('Москва')].reset_index()

## Работаем с пропусками

In [8]:
#Сколько NaN и где? (проверяю по мере заполнения)
df.isna().sum()

index                     0
ID  объявления            0
Количество комнат       535
Метро                   346
Адрес                     0
Площадь, м2               0
Дом                       0
Парковка              11174
Цена                      0
Ремонт                 2463
Площадь комнат, м2     7228
Балкон                 6630
Окна                   5150
Санузел                2041
Дополнительно           272
Высота потолков, м     9202
Лифт                   4192
Мусоропровод           8007
dtype: int64

In [9]:
#Помучаемся с адресами... Убираем шоссе оттуда, где оно есть
df['Адрес'] = [x.split('ш. ')[0] for x in df['Адрес']]

In [10]:
#Создаем список всех возможных улиц для редактирования
lst = df['Адрес'].tolist()

In [11]:
#Манипуляции с адресами..
lst1 = [str(index) + ', ' + features for index, features in enumerate(lst)]

In [12]:
lst2 = [x.split(',') for x in lst1]
lst3 = [' '.join(' '.join(x).strip().split()[2:-1]) for x in lst2]

#Обновляем колонку в df
df['Адрес'] = lst3

In [13]:
#Парковка (заменяем NaN)
df['Парковка'] = df['Парковка'].fillna('бесплатная во дворе')

In [14]:
#Количество комнат (если длина строки больше 1 - значит там не только значение, вытаскиваем его по индексу)
def room_count(s):
    if len(s) > 1:
        return int(s.split(',')[0])
    else:
        return int(s)
df['Количество комнат'] = df['Количество комнат'].fillna('0')
df['Количество комнат'] = df['Количество комнат'].apply(room_count)

In [15]:
#Метро (заполняем NaN)
df['Метро'] = df['Метро'].fillna('м. Отсутствует рядом (0 мин пешком)')
df['Метро'] = [x.split(' (')[0] for x in df['Метро']]
df['Метро'] = [x.split('. ')[1] for x in df['Метро']]

In [16]:
df['Ремонт'] = df['Ремонт'].fillna('Без ремонта')

In [17]:
#Площадь - заполним пробелы
df['Площадь общая, м2'] = [float(x.split('/')[0]) for x in df['Площадь, м2']]

In [18]:
#Выкинем теперь площадь комнат
df = df.drop(columns=['Площадь комнат, м2', 'Площадь, м2'])

In [19]:
#Балконы - заполним NaN, разделим по двум столбцам
df['Балкон'] = df['Балкон'].fillna('Балкон (0)')
df['Лоджия'] = [x.split(' ')[-1] if x.split(' ')[-2] == 'Лоджия' else 0 for x in df['Балкон']]
df['Балкон'] = [x.split(' ')[1] if x.split(' ')[0] == 'Балкон' else 0 for x in df['Балкон']]

In [20]:
#Убрать скобки у балконов
df['Балкон'] = [int(x[1]) if type(x) == str else 0 for x in df['Балкон']]
df['Лоджия'] = [int(x[1]) if type(x) == str else 0 for x in df['Лоджия']]

In [21]:
#Окна - заполним NaN 
df['Окна'] = df['Окна'].fillna('На улицу или двор')

In [22]:
#Санузлы - делаем как с балконами
df['Санузел'] = df['Санузел'].fillna('Совмещенный (1)')
df['Санузел разд.'] = [x.split(' ')[-1] if x.split(' ')[-2] == 'Раздельный' else 0 for x in df['Санузел']]
df['Санузел совм.'] = [x.split(' ')[1] if x.split(' ')[0] == 'Совмещенный' else 0 for x in df['Санузел']]

In [23]:
#Вторая часть про санузлы - вытащили значения, сделали из них int принудительно :)
df['Санузел разд.'] = [int(x[1]) if type(x) == str else 0 for x in df['Санузел разд.']]
df['Санузел совм.'] = [int(x[1]) if type(x) == str else 0 for x in df['Санузел совм.']]
df = df.drop(columns=['Санузел'])

In [24]:
#Разберемся с колонкой "Дополнительно". Логика такая -> не прописано - значит квартира пустая
df['Дополнительно'] = df['Дополнительно'].fillna('Отсутствует')

In [25]:
#Сделаем в колонке два вывода - "Присутствуют удобства" если там все, кроме "Отсутствует", и "Отсутствуют удобства" в ином случае
df['Дополнительно'] = ['Отсутствуют удобства' if x == 'Отсутствует' else 'Присутствуют удобства' for x in df['Дополнительно']]

In [26]:
#Потолки... настало ваше время... Пропуски заполним средним значением, округлим после точки до двух символов
#Предварительно переведем см в м (надеемся, что трехзначные числа - это см)
df['Высота потолков, м'] = [x / 100 if x > 30 else x for x in df['Высота потолков, м']]
df['Высота потолков, м'] = [x / 10 if x > 20 else x for x in df['Высота потолков, м']]
df['Высота потолков, м'] = df['Высота потолков, м'].fillna(round(df['Высота потолков, м'].mean(), 2))

In [27]:
#Из колонки Дом получить колонку Дом и Этаж
df['Тип дома'] = [x.split(', ')[-1] if len(x.split(', ')[-1]) > 6 else 'Неизвестно' for x in df['Дом']]
df['Количество этажей'] = [int(x.split('/')[1].split(',')[0]) for x in df['Дом']]
df['Этаж квартиры'] = [int(x.split('/')[0]) for x in df['Дом']]
df = df.drop(['Дом'], axis=1)

In [28]:
#Лифты. Заполним NaN - пусть будет Пасс (0), Груз (0), если меньше 5 этажей
df['Лифт'] = [x if x == x else ['Пасс (1), Груз (1)' if df['Количество этажей'].iloc[i]>5 else 'Пасс (0), Груз (0)'][0]for i, x in enumerate(df['Лифт'])]

In [29]:
#Разделим лифты на две колонки - груз и пасс, удалим старую колонку
df['Лифт груз.'] = [x.split(' ')[-1] if x.split(' ')[-2] == 'Груз' else 0 for x in df['Лифт']]
df['Лифт пасс.'] = [x.split(' ')[1] if x.split(' ')[0] == 'Пасс' else 0 for x in df['Лифт']]

In [30]:
#Заменим у лифтов значения на type=int + выкинем ненужную колонку
df['Лифт груз.'] = [int(x[1]) if type(x) == str else 0 for x in df['Лифт груз.']]
df['Лифт пасс.'] = [int(x[1]) if type(x) == str else 0 for x in df['Лифт пасс.']]
df = df.drop(columns=['Лифт'])

In [31]:
#Обработаем мусоропровод от NaN
df['Мусоропровод'] = df['Мусоропровод'].fillna('Нет')

## Итоговый DF после удаления всех NaN:

In [32]:
df

,index,ID объявления,Количество комнат,Метро,Адрес,Парковка,Цена,Ремонт,Балкон,Окна,Дополнительно,"Высота потолков, м",Мусоропровод,"Площадь общая, м2",Лоджия,Санузел разд.,Санузел совм.,Тип дома,Количество этажей,Этаж квартиры,Лифт груз.,Лифт пасс.
0,0,271271157,4,Смоленская,улица Новый Арбат,подземная,500000,Дизайнерский,0,На улицу или двор,Присутствуют удобства,3.00,Да,200.0,0,0,1,Монолитный,16,5,1,4
1,1,271634126,4,Смоленская,улица Новый Арбат,подземная,500000,Дизайнерский,0,На улицу и двор,Присутствуют удобства,3.50,Нет,198.0,0,1,2,Монолитно-кирпичный,16,5,1,1
2,2,271173086,4,Смоленская,улица Новый Арбат,подземная,500000,Евроремонт,0,На улицу и двор,Присутствуют удобства,3.20,Нет,200.0,0,0,3,Неизвестно,16,5,0,1
3,3,272197456,4,Смоленская,переулок Плотников,подземная,400000,Евроремонт,0,На улицу и двор,Присутствуют удобства,3.20,Нет,170.0,0,0,3,Неизвестно,6,5,0,1
4,4,273614615,2,Арбатская,улица Новый Арбат,бесплатная во дворе,225000,Евроремонт,0,На улицу и двор,Присутствуют удобства,3.90,Да,58.0,0,0,2,Панельный,26,12,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19732,23363,215565511,0,Говорово,Боровское шоссе,бесплатная во дворе,42000,Евроремонт,1,На улицу или двор,Присутствуют удобства,2.76,Нет,35.0,0,0,1,Неизвестно,14,10,1,1
19733,23364,274654844,1,Солнцево,Производственная улица,бесплатная во дворе,45000,Евроремонт,0,Во двор,Присутствуют удобства,2.76,Нет,38.7,1,0,1,Монолитный,18,5,1,1
19734,23365,268679909,2,Солнцево,Боровский проезд,бесплатная во дворе,50000,Дизайнерский,1,На улицу и двор,Присутствуют удобства,2.76,Нет,43.1,0,0,1,Кирпичный,5,5,0,0
19735,23366,274807525,2,Солнцево,улица Богданова,наземная,55000,Евроремонт,0,Во двор,Присутствуют удобства,2.65,Да,52.5,1,1,1,Монолитный,23,8,0,3
19736,23367,274672243,2,Говорово,улица Богданова,бесплатная во дворе,57000,Косметический,0,Во двор,Присутствуют удобства,2.76,Да,90.0,1,1,0,Панельный,23,6,0,3

# Поменяем названия согласно ТЗ.

In [33]:
#Создадим словарь для переименования колонок
new_column_names = {
    'ID  объявления':'ID',
    'Количество комнат':'room_number',
    'Метро':'subway',
    'Адрес':'address',
    'Парковка':'parking',
    'Ремонт':'home_renovation',
    'Балкон':'balcony',
    'Окна':'windows',
    'Дополнительно':'additional_amenities',
    'Высота потолков, м':'ceiling_height',
    'Мусоропровод':'garbage_chute',
    'Площадь общая, м2':'total_area',
    'Площадь жилая, м2':'living_area',
    'Площадь кухня, м2':'kitchen_area',
    'Лоджия':'loggia',
    'Санузел разд.':'separate_bathroom',
    'Санузел совм.':'shared_bathroom',
    'Тип дома':'building_type',
    'Количество этажей':'floors_number',
    'Этаж квартиры':'apartment_floor',
    'Лифт груз.':'freight_elevator',
    'Лифт пасс.':'passenger_elevator',
    'Цена':'price'}

In [34]:
df = df.rename(columns=new_column_names)
df = df.drop(columns=['index'])

In [35]:
#Выгрузим готовый DataFrame в .csv формат
df.to_csv('data.csv', index=False)

# Релиз 3.0

In [36]:
#Поработаем с выбросами
df_v2 = df[df['total_area'] < 600].reset_index(drop = True)
df_v2 = df[df['price'] < 1500000].reset_index(drop = True)
df_v2 = df[df['price'] > 20000].reset_index(drop = True)

In [37]:
#Сделаем словари для замены категориальных признаков на числовые (метро и адрес рассмотрим отдельно)
parking = {x: i for i, x in enumerate(sorted(list(set(df['parking']))))}
home_ren = {x: i for i, x in enumerate(sorted(list(set(df['home_renovation']))))}
window = {x: i for i, x in enumerate(sorted(list(set(df['windows']))))}
add_am = {x: i for i, x in enumerate(sorted(list(set(df['additional_amenities']))))}
chute = {x: i for i, x in enumerate(sorted(list(set(df['garbage_chute']))))}
building = {x: i for i, x in enumerate(sorted(list(set(df['building_type']))))}

In [38]:
#Заменим данные в таблице
df_v2['parking'] = [parking[x] for x in df_v2['parking']]
df_v2['home_renovation'] = [home_ren[x] for x in df_v2['home_renovation']]
df_v2['windows'] = [window[x] for x in df_v2['windows']]
df_v2['additional_amenities'] = [add_am[x] for x in df_v2['additional_amenities']]
df_v2['garbage_chute'] = [chute[x] for x in df_v2['garbage_chute']]
df_v2['building_type'] = [building[x] for x in df_v2['building_type']]

In [39]:
#Функция для кодировки адреса и метро
def cat_code(df, cat, real):
    return df[cat].map(df.groupby(cat)[real].mean())

In [40]:
#Кодируем метро
df_v3 = df_v2.copy()
df_v3['subway'] = cat_code(df_v3, 'subway', 'price')

In [41]:
#Кодируем адреса
df_v3['address'] = cat_code(df_v3, 'address', 'price')

In [42]:
#Используем dummy для лучшего обучения
cat_features = ['parking','home_renovation', 'windows', 'additional_amenities', 'garbage_chute', 'building_type']
features = ['room_number', 'balcony', 'ceiling_height','total_area','living_area','kitchen_area','loggia','separate_bathroom','shared_bathroom','floors_number','apartment_floor','freight_elevator','passenger_elevator']

for f in cat_features:
    df_v3 = pd.concat([df_v3, pd.get_dummies(df_v3[f], prefix = f)], axis = 1)
    features.extend([col for col in df_v3 if col.startswith(f + '_')])
features

['room_number',
 'balcony',
 'ceiling_height',
 'total_area',
 'living_area',
 'kitchen_area',
 'loggia',
 'separate_bathroom',
 'shared_bathroom',
 'floors_number',
 'apartment_floor',
 'freight_elevator',
 'passenger_elevator',
 'parking_0',
 'parking_1',
 'parking_2',
 'parking_3',
 'parking_4',
 'parking_5',
 'home_renovation_0',
 'home_renovation_1',
 'home_renovation_2',
 'home_renovation_3',
 'windows_0',
 'windows_1',
 'windows_2',
 'windows_3',
 'additional_amenities_0',
 'additional_amenities_1',
 'garbage_chute_0',
 'garbage_chute_1',
 'building_type_0',
 'building_type_1',
 'building_type_2',
 'building_type_3',
 'building_type_4',
 'building_type_5',
 'building_type_6',
 'building_type_7',
 'building_type_8',
 'building_type_9']

In [43]:
#Используем One-Hot 
for col in cat_features:
    if df_v3[col].dtype == 'object':
        df_v3[col] = pd.factorize(df_v3[col])[0]

In [44]:
#Вместо True False сделаем 1 и 0
def true_or_false(x):
    if x == True:
        return 1
    elif x == False:
        return 0
    else:
        return x

need_to_change = ['parking_0', 'parking_1', 'parking_2', 'parking_3', 'parking_4', 'parking_5',
       'home_renovation_0', 'home_renovation_1', 'home_renovation_2', 'home_renovation_3', 
                  'windows_0', 'windows_1', 'windows_2', 'windows_3',
       'additional_amenities_0', 'additional_amenities_1', 'garbage_chute_0',
       'garbage_chute_1', 'building_type_0', 'building_type_1',
       'building_type_2', 'building_type_3', 'building_type_4',
       'building_type_5', 'building_type_6', 'building_type_7',
       'building_type_8', 'building_type_9']
for i in need_to_change:
    df_v3[i] = df_v3[i].apply(true_or_false)

In [45]:
#Просмотр DataFrame перед выгрузкой
df_v3

,ID,room_number,subway,address,parking,price,home_renovation,balcony,windows,additional_amenities,ceiling_height,garbage_chute,total_area,loggia,separate_bathroom,shared_bathroom,building_type,floors_number,apartment_floor,freight_elevator,passenger_elevator,parking_0,parking_1,parking_2,parking_3,parking_4,parking_5,home_renovation_0,home_renovation_1,home_renovation_2,home_renovation_3,windows_0,windows_1,windows_2,windows_3,additional_amenities_0,additional_amenities_1,garbage_chute_0,garbage_chute_1,building_type_0,building_type_1,building_type_2,building_type_3,building_type_4,building_type_5,building_type_6,building_type_7,building_type_8,building_type_9
0,271271157,4,313196.969697,331489.361702,5,500000,1,0,3,1,3.00,0,200.0,0,0,1,4,16,5,1,4,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0
1,271634126,4,313196.969697,331489.361702,5,500000,1,0,2,1,3.50,1,198.0,0,1,2,3,16,5,1,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0
2,271173086,4,313196.969697,331489.361702,5,500000,2,0,2,1,3.20,1,200.0,0,0,3,5,16,5,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0
3,272197456,4,313196.969697,397500.000000,5,400000,2,0,2,1,3.20,1,170.0,0,0,3,5,6,5,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0
4,273614615,2,340903.614458,331489.361702,0,225000,2,0,2,1,3.90,0,58.0,0,0,2,6,26,12,1,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19694,215565511,0,57378.557143,51985.074627,0,42000,2,1,3,1,2.76,1,35.0,0,0,1,5,14,10,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,0
19695,274654844,1,46279.661017,54850.000000,0,45000,2,0,0,1,2.76,1,38.7,1,0,1,4,18,5,1,1,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0
19696,268679909,2,46279.661017,44000.000000,0,50000,1,1,2,1,2.76,1,43.1,0,0,1,2,5,5,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0
19697,274807525,2,46279.661017,50307.692308,3,55000,2,0,0,1,2.65,0,52.5,1,1,1,4,23,8,0,3,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0
19698,274672243,2,57378.557143,50307.692308,0,57000,3,0,0,1,2.76,0,90.0,1,1,0,6,23,6,0,3,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0

In [48]:
#Уберем цену в конец графика
last_column = df_v3.pop('price')
df_v3.insert(df_v3.shape[1], 'price', last_column)

In [49]:
#Выгружайте его, с него достаточно!
df_v3.to_csv('VRNENT_data.csv', index=False)